### ISSUE TITLE
Support for SettingsController in the Scene page on website

### ISSUE THREAD

**Issue by marcoaltomonte** [sinricpro/feature-requests#18]
I would like to setup multiple light scenario on my esp32 light.
The simplest way I thought of was to create a new Scene on the website, sending a specific if/key value to the SettingsController of my device. 
However, I can't find a "Setting" action in the Action combobox (just set powerstate, color, ...). Would it be possible to add it?

**Comment by kakopappa** [comment]
Have you thought of creating a custom device type for this and use a mode
controller with the different modes for each scenario.

SettingsController is not meant to do this.

**Comment by marcoaltomonte** [comment]
Thanks. I didn't know about custom devices. It's unfortunate that google home is not supported: I will wait for it!
