### ISSUE TITLE
sensor not available for starter google home

### ISSUE THREAD

**Issue by sebastienliron** [sinricpro/feature-requests#19]
Contact sensor configured and working fine in google home ( except for the part that we can't change the power state )

BUT, I can't use it as a starter, is it because of the type, or is this some missing implementation in the sensor for google home ?

additional question : is it possible to have a power state + some action and to be able to use it as starter in google home ?

**Comment by kakopappa** [comment]
Hi @sebastienliron 

Thanks for reporting this issue. 

According to this article, https://9to5google.com/2022/11/01/setup-google-homes-device-triggered-routines/ Contact sensor type is not supported as a starter yet. As a workaround, if possible try a Motion sensor instead of Contact sensor. I can see my Sinric pro motion sensor is available in Google Home app as a routine starter

**Comment by sebastienliron** [comment]
hello @kakopappa, I already tried motion sensor, which indeed seems to be the best option.
But it does not appears on google home ( as per the sinric pro page, motion sensor is not yet available on google home )

That is why I tried the contact sensor, I might have to use two switch to handle my case.

Thank you for the info on google home starter routine, I imagined it was the case.

**Comment by kakopappa** [comment]
@sebastienliron you are correct. Have you tried Door bell sensor? I can see the doorbell device type in Google Home app.

![image](https://user-images.githubusercontent.com/7474406/210180118-0aa9c480-cb76-498b-904a-99295e3811c4.png)

**Comment by sebastienliron** [comment]
@kakopappa yes it works better with this one, thank you for the support !

**Comment by kakopappa** [comment]
Great!

Surprisingly GH still doesn’t have Motion Sensor type

https://developers.home.google.com/cloud-to-cloud/traits

**Comment by sebastienliron** [comment]
I can see this : https://developers.home.google.com/cloud-to-cloud/traits/objectdetection?hl=en

I have no clue about how it is coded on sinric end, I could have a look if pointed in the good direction.

In any case the lack of power state is an issue on GH end IMHO

**Comment by kakopappa** [comment]
Sorry object detection is not supported

**Comment by kakopappa** [comment]
closing this issue since you can use a doorbell or two switch devices. If you have any issues please create another issue
