### ISSUE TITLE
[Bug] [iOS app] Device template Toggle switches always stay off

### ISSUE THREAD

**Issue by arielscarpinelli** [sinricpro/feature-requests#21]
If you touch them, they do send a toggle on request to the device, but no matters if the device responds ok, they stay off in the UI. You can check also in the web the status is actually on. Exiting the screen and entering again still shows them off.

**Comment by kakopappa** [comment]
Hi @arielscarpinelli 

Thanks for reporting this issue and the others. 

I can reproduce this locally. I will fix the bugs first and release a version ASAP

**Comment by kakopappa** [comment]
Will be fixed in v2.17.2. Will let you know when it's released.

https://user-images.githubusercontent.com/7474406/210951516-7fbf5ca4-cb6b-4691-809d-76fb5fe3cdeb.mp4

**Comment by kakopappa** [comment]
Hi @arielscarpinelli 

I have updated the Portal (Web UI) and microservices already so fixes related to the Portal are available now.  App fixes are waiting for approval from AppStore they should be available within the next 8 hours.

**Comment by arielscarpinelli** [comment]
Works fine now! Thanks.
