### ISSUE TITLE
Ability to create automations (routines) according to sensor values ​​and other logics

### ISSUE THREAD

**Issue by danielandradam** [sinricpro/feature-requests#29]
I really like the Sinric system and have been using it since the first version in projects using arduino. 

I would like to know if it would be possible to implement the capability of **more complex automations.** Currently, it is only possible to activate relays at certain times. It would be interesting to be able to include the ability to, for example, if the value of a certain sensor is greater than xx and the time is yy then trigger the zzz device.

**Comment by kakopappa** [comment]
Hi @danielandradam 

Thanks! 

This is in the plan. Hopefully can finish this by mid-end this year. For now please use Alexa App or SmartThings app (better)

**Comment by danielandradam** [comment]
I understood! My only problem is that I would like to do automation logic via software and not directly in hardware.

So far **I can't read an analog or digital signal from the arduino for use in some automation logic.**

By Sinric when I add an "other" device with the range function I can read any value of the arduino, but when i try read these values on smartthing or google home cannot read these values.

If there was a device model in Sinric, such as the temperature sensor that could be changed to receive an analog or digital value, maybe that would solve it....

Thanks for any help!

**Comment by kakopappa** [comment]
> Hi @danielandradam
> 
> Thanks!
> 
> This is in the plan. Hopefully can finish this by mid-end this year. For now please use Alexa App or SmartThings app (better)

Took almost 1 year but got it done. Automations are now available.
