### ISSUE TITLE
add /products

### ISSUE THREAD

**Issue by Geromatic** [sinricpro/feature-requests#33]
I checked the api documentation and it is missing /products page.  how do I know what device type that I can make.

**Comment by Geromatic** [comment]
```
var request = require("request");
var options = { 
  method: 'GET',
  url: 'https://api.sinric.pro/api/v1/products/',
  headers: 
  {   'Authorization': 'Bearer <TOKEN HERE>',
      'Content-Type': 'application/x-www-form-urlencoded' 
  }
};

request(options, function (error, response, body) {
  if (error) throw new Error(error);
  console.log(body);
});
```
I tried this code and sends me back result code 200 but does not provide me any data back. so I am assuming its coded in as a dummy function till a future update

**Comment by kakopappa** [comment]
your code works fine for me.
![image](https://user-images.githubusercontent.com/7474406/223346379-fff35ef4-d9e6-49bc-917b-060a2aa78d17.png)

**Comment by Geromatic** [comment]
hmm im using arduino so it might be too large of a payload

**Comment by kakopappa** [comment]
They are static, so you could hardcode the IDs

**Comment by Geromatic** [comment]
is there a way just to get the a simplified version that shows the productids similar to Get default list of room names
nodejs command

**Comment by kakopappa** [comment]
no, there's not. I think I best option is to hard-code the ids. API is not written to be processed by microcontroller.

**Comment by sivar2311** [comment]
@Geromatic If you use the ArduinoJson library, you can set filters to reduce the size. [See example](https://arduinojson.org/v6/example/filter/).

But as Kakopappa said: It is not meant to call the API from an Arduino. 
If I may ask: What do you intend to do?

**Comment by Geromatic** [comment]
technically I am not using nodejs.  I am converting the commands to arduino http. 

https://github.com/sinricpro/non-sdk-issues/issues/53

**Comment by sivar2311** [comment]
> technically I am not using nodejs
Yes, we are talking about Arduino.
It's about how you parse the JSON response.

If you use the ArduinoJson library you can easily set filters (see my post before) to reduce the JSON response and filter out only what you need. 

I'm still interested in understanding what you're trying to do.

**Comment by kakopappa** [comment]
Me too

**Comment by sushantr5** [comment]
How can I create my own product?

**Comment by kakopappa** [comment]
Hi @sushantr5 

There are custom device types and built-in device types. Built-in are defined by us for common use cases and custom are created by the end-user for their edge cases. 

If you want to share a custom device template with someone else then you can export the custom device temple to json format and share it. so the other person can import it.

Different fan speeds can be defined at the time of creating fan device (others tab)

If you have any other questions, please create a new issue

**Comment by sushantr5** [comment]
@kakopappa 

Thank you for your reply. But I want to create this custom device automatically through API may be. I want to make this process as easy as possible in tasmota.

1. User adds authorization details in Tasmota
2. Device shall be created automatically in sinric.pro

so for this purpose, when user enters credentials in Tasmota, I will call create device API. For this purpose Product is needed, Product may not be as per the template defined. So if we take basic use case, I want to control multiple relays through Tasmota and Sinric.pro, then in this case product details might be dependent on number of relays.

So I want to embed Product definition in Tasmota which can be customized according to the need. Other option I thought of adding one device for one relay, but it will consume device licenses in Sinric.pro. That is why I would like to create One device with 4 Relays.
