### ISSUE TITLE
Homebridge Integration

### ISSUE THREAD

**Issue by fpto** [sinricpro/feature-requests#41]
To many of us who are invested in Apples ecosystem an alternative to get our non-native homekit devices into Apple home is using Homebridge: https://homebridge.io/ 

For this you could develop a Homebridge Sinricpro Plugin that connects Homebridge with Sinric's API
or 
Simply make Sinric complatible with MQTT (https://mqtt.org/) a wide use protocol for IOT
Like this similar service did: https://www.docu.smartnest.cz/homebridge-integration

To be clear we are not asking for Native Homekit support, we would be more than happy with work arounds like Homebridge or MQTT.

**Comment by kakopappa** [comment]
Hi @fpto 

If you are looking for a quick win, try Homebridge [API](https://github.com/homebridge/homebridge-config-ui-x/wiki/API-Reference). You should be able to send the PUT command via ESP8266/ESP32 to the Homebridge API.

CURL examples: 
https://github.com/homebridge/homebridge/issues/2512#issuecomment-619303434

Another option would be to use Node-RED with Sinric Pro  [node-red](https://github.com/sinricpro/node-red-contrib-sinric-pro) plugin 

The proper way to implement this is via a plug-in (same as Node-RED). Unfortunately, we do not have the capacity to do this now. perhaps in the future will take a look. If you are willing to take on the challenge, I can help you with the APIs.

**Comment by kakopappa** [comment]
Hi @fpto 

I have started working on a homebridge-sinricpro plugin. 

Is there any specific device type you are after? planning to implement Switch for the first release and followed by others.

https://github.com/sinricpro/homebridge-sinricpro

**Comment by fpto** [comment]
Hi there
Great news!

Thermostats and temperature sensors are the devices I use. It would be great if they are supported.

**Comment by kakopappa** [comment]
Done. https://www.npmjs.com/package/homebridge-sinricpro
