### ISSUE TITLE
There's no way to change the AC fan speed from the app

### ISSUE THREAD

**Issue by albertvaka** [sinricpro/feature-requests#5]
Even though the [SDK exposes a `RangerController` capability](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/src/SinricProWindowAC.h#L41), which I assume can be used to change the fan speed, there's no way to set this from the UI:

![Screenshot_20220627-115240](https://user-images.githubusercontent.com/980842/176860016-377889ee-91df-4d97-90c3-3f9a92192078.png)

**Comment by kakopappa** [comment]
Noted. Thanks for reporting this issue. Will fix it  the next version

**Comment by kakopappa** [comment]
Done. Will be released with the next version update in a few hours from now. 

![ac_unit_ui_update](https://user-images.githubusercontent.com/7474406/187596228-fa32cb49-5ae7-4250-b85b-9237e05cb48b.png)

**Comment by albertvaka** [comment]
That's so cool, you are the best! ❤️

**Comment by albertvaka** [comment]
I just tested this and it works perfectly, so I'm closing the issue. Thanks again :D
