### ISSUE TITLE
Events for current and target temperature for a thermostat in node.js? 

### ISSUE THREAD

**Issue by emnik** [sinricpro/feature-requests#51]
Hi! Is it possible to set the current and the target temperature for a thermostat via  raiseEvent in node.js?

**Comment by kakopappa** [comment]
@emnik Thanks. Please use

`raiseEvent(sinricpro, eventNames.currentTemperature, 'DeviceId', { "humidity": 75.3, "temperature": 24});`

**Comment by emnik** [comment]
Yes this works for current temperature! thanks!

Though an event for Target temperature is also a must to be able to keep alexa thermostat in sync with the hardware thermostat.

In the past (before sinric pro you had these:
1. Current and Target
var wsdata = {"action":"SetTemperatureSetting", "deviceId":thermostatId, "value":{"temperatureSetting":{"setpoint": 25, "scale":"CELSIUS", "ambientTemperature": 24}}}

2. Target
var wsdata = {"action":"SetTargetTemperature", "deviceId":thermostatId, "value":{"targetSetpoint":{"value":25, "scale":"CELSIUS"}}}

**Comment by kakopappa** [comment]
Hi @emnik  

Yeah, this is what we had in sinric.com days. we have moved to a unified structure with Sinric Pro to support Google Home/SmartThings. You can find the example messages here: https://github.com/sinricpro/sample_messages

for setTargetTemperature, please check other issue ticket for details: https://github.com/sinricpro/nodejs-sdk/issues/39

**Comment by emnik** [comment]
@kakopappa
It seems there are not events for SetTargetTemperature and AdjustTargetTemperature...

Could you please also add events for 
**SetTargetTemperature** and **AdjustTargetTemperature**?

I' ve tried adding SetTargetTemperature to the eventNames and actionArr in the lib/events/event_handler.js but it does not work...

SetTargetTemperature is crusial... AdjustTargetTemperature not that much :-)

**Comment by kakopappa** [comment]
for `SetTargetTemperature ` please refer to the example.

https://github.com/sinricpro/nodejs-sdk/blob/master/examples/thermostat/app.js

`AdjustTargetTemperature` working in it. will update you when it's ready.

**Comment by kakopappa** [comment]
I have released a new version of the sdk 2.10.1 

Complete Example here
https://github.com/sinricpro/nodejs-sdk/blob/master/examples/thermostat/app.js

**Comment by kakopappa** [comment]
can you share more details on how are you controlling the thermostat, please?

**Comment by emnik** [comment]
@kakopappa In my app, one can set the thermostat's target temp temp either manually (via a slider) or auto (via schedulling) and there is also enable / disable modes like on / off.
What I'm trying to do is to keep the thermostat's state in sync with Alexa's thermostat (sinric.pro device) so I would be able to see in the Alexa app the current temperature, the target temperature and the status and change whaterver accordingly by voice or by app.

I am already using the targetTemperature callback. AdjustTargetTemperature would be nice to be implemented as a **callback** too. Something like:
```
const adjustTargetTemperature = async (deviceid, data) => {
  // data would by like {"value":{"targetSetpointDelta":{"value":1,"scale":"CELSIUS"}}}
  console.log(deviceid, JSON.stringify(data));
  return true;
}
```

I also need the corresponsive **event** for the targetTemperature to update alexa's thermostat when there is a manual or scheduled change!
Something like:
`raiseEvent(sinricpro, eventNames.SetTargetTemperature, device1, {"value":{"targetSetpoint":{"value":16, "scale":"CELSIUS"}}});`

You can see my code in [https://github.com/emnik/pyre/blob/master/my_modules/alexa.js](https://github.com/emnik/pyre/blob/master/my_modules/alexa.js)

**Comment by emnik** [comment]
@kakopappa Question: what is temperature supposed to do when return { success: true, temperature: globalTemperature };

I used to just get the delta value (-1, +2, ... whatever) and update my target temperature by target = target + delta. Then I sent the new target back to Alexa  (here also the setTargetThermostat event is needed!). Is it supposed to update the new target in the sinric device automatically? Though this doesn't seem to happen... Whatever the delta value and the target Alexa says "The HEAT set to 24!!!"

Also have in mind that raiseEvent(sinricpro, eventNames.thermostatMode ..) works but in the portal you need to refresh the page to see the new mode.

**Comment by kakopappa** [comment]
Is this question about phrase: Alexa to make it cooler or warm here ?

When you ask Alexa to make it cooler or warm here, it would send +2, -2 to Sinric Pro server, The server will forward this to your device. 

` { success: true, temperature: `globalTemperature `}; ` 

here `globalTemperature`  is the current temperature the thermostat is set to after adjustment. 

When you send this to Sinric Pro server, it will save and notify Alexa current temperature the thermostat is set to. 

Will take a look at the refresh issue in the portal. is there anything else to be checked/fixed?

**Comment by emnik** [comment]
@kakopappa 
so the globalTemperature is the new target temperature! not the current temperature! Though it doesn't seem to update the target...

If I say "Alexa set thermostat to 20 degrees" it sets it fine.
Then "Alexa make thermostat cooler" 
What happens is:
AdjustTargetTemperature returns -1 and I set the globalTemperature to 19 (in the return object) **but** Alexa
- does not update the new target setpoint 
- reports by saying the Heat set to 24 <- always! Whatever the new target
- the target setpoint in sinric portal does not change and if I refresh it gets from 20 to --

Finally what about a setTargetTemperature event? This is so much needed...

**Comment by kakopappa** [comment]
Hi @emnik 

i have released a new version (2.11.1) with `targetTemperature` added. 

`raiseEvent(sinricpro, eventNames.targetTemperature, "deviceId", { temperature: Math.floor(Math.random() * 60) });`

Will take a look at adjust issue in a bit

**Comment by kakopappa** [comment]
have released another version (2.11.2) with  `AdjustTargetTemperature ` fix.

**Comment by emnik** [comment]
@kakopappa with 2.11.2 my sinric device cannot connect... Shows offline! I've tried deleting and making a new device with new deviceId...same :-(
Didn't make any changes to my code though...

**Comment by kakopappa** [comment]
Hi @emnik pls check again with 2.11.3.

**Comment by emnik** [comment]
@kakopappa Everything seems to work now expect the event for powerState!!!

**Comment by kakopappa** [comment]
Hi @emnik pls check again with 2.11.4 when u get a chance.

**Comment by emnik** [comment]
@kakopappa Hi! Everything seems to work fine!!! Thank you very much!!! You are doing a fantastic work!
