### ISSUE TITLE
[App][BUG] Template device with readonly toggle does not show

### ISSUE THREAD

**Issue by arielscarpinelli** [sinricpro/feature-requests#56]
- Create a template device with a toggle capability set to read only.
- Add a device with that template
- Open the device in the app and check the toggle row

Expected:
- The row shows the current status (on/off or true/false?) for that toggle

Actual
- Only the toggle name appears, but nothing else.

**Comment by kakopappa** [comment]
Thanks for reporting this. fix (2.24.3) should be available in Google Play a few hours from now. 
![image](https://github.com/sinricpro/feature-requests/assets/7474406/e38b6da0-b526-4485-be51-56d849e2fb79)
