### ISSUE TITLE
undo delete of the device

### ISSUE THREAD

**Issue by klaudyu** [sinricpro/feature-requests#6]
I have an device that I don't have easy access to. By mistake I deleted the device from sinric and I cannot add it back. Is there a possibility to add it back? It's a bit frustrating to have to open the device to programm it again when I just need to be able to put the id back on the switch.

**Comment by kakopappa** [comment]
Thanks. To avoid this from happening will add a “are you sure want to
delete?” dialog in the future releases

**Comment by kakopappa** [comment]
Delete confirmation is not available.


https://user-images.githubusercontent.com/7474406/187598414-5a74cd42-77d5-406e-b724-f5afef2b2a5f.mp4

**Comment by kakopappa** [comment]
this is already in production. closing
