### ISSUE TITLE
[Bug] [Portal] Device with Range capability in Kilograms displays in grams on the Dashboard.

### ISSUE THREAD

**Issue by joseportillodev** [sinricpro/feature-requests#60]
Dear developers,

Description:

- When I create a device using a custom template with a Range capability (units of measure: Kilograms), the displayed units on the dashboard are grams (g).

How to reproduce it:

- Create a new device template with a Range capability. Set the units of measure to Kilograms. Set it to read-only (non-controllable)
- Create a device based on the template.
- Update device measurements i.e. from an ESP8266 board using the SinricPro SDK and a minimal sketch to update the range value on connect (SinricPro.onConnected callback).
- Observe device data displayed on the Dashboard of the Portal.

Screenshots:

- Units set on the Range capability:

<img width="388" alt="Captura de pantalla 2024-04-24 a las 22 04 03" src="https://github.com/sinricpro/feature-requests/assets/166513883/032d0a76-72b7-4aaa-9bd6-2aae14a2f98e">

- Units displayed on the dashboard:

<img width="440" alt="Captura de pantalla 2024-04-24 a las 22 05 52" src="https://github.com/sinricpro/feature-requests/assets/166513883/f74f99dd-9edb-4c2a-acd8-19439557e908">

- On the other hand, on the iOS App they are displayed properly (kg):

<img width="440" alt="IMG_0528" src="https://github.com/sinricpro/feature-requests/assets/166513883/dce1a7a0-7c02-4869-afb8-1da978b5411a">

Thank you

**Comment by kakopappa** [comment]
Thanks for reporting this issue. 

I have uploaded the fix to the production system now. It's fixed with v2.42.6. 

Your previous issue: https://github.com/sinricpro/esp8266-esp32-sdk/issues/373 will likely be released to the production system this Friday.

Keep up the good work!

**Comment by joseportillodev** [comment]
Perfect, thank you. Closing this issue on my part.
