### ISSUE TITLE
clear energy sensor historical data

### ISSUE THREAD

**Issue by Ntranx** [sinricpro/feature-requests#64]
I want to know if there is any way to delete the data from the energy meter. I am doing tests and every time I try and make a mistake I have to delete the sensor and add another one. I would like something similar like the temperature sensor.
or change the month-end cycles since my billing cycle per month is cut every 25th of the month and not every 30th. Is there a way to change these cycles so that it calculates the energy per month for personalized periods?

**Comment by kakopappa** [comment]
Hi @Ntranx 

Thanks for the suggestion. We will add the **erase** feature. Will update this ticket when it's available.

**Comment by Ntranx** [comment]
still no update?

**Comment by kakopappa** [comment]
We have added this in the latest version however, it's not in the production system yet. Production release is planned for 5th/Aug

![image](https://github.com/user-attachments/assets/ddd3df14-a902-44f9-8077-a034a0570892)

**Comment by Ntranx** [comment]
I already tried it and it's excellent
thanks a lot
