### ISSUE TITLE
Devices not show on Alexa routines on events Power On/Off

### ISSUE THREAD

**Issue by marceloc312** [sinricpro/feature-requests#65]
When I create an routine for device not possible create for device change to ON/OFF

**Comment by kakopappa** [comment]
Hi,which device type are you using?

**Comment by marceloc312** [comment]
As far as I could see, no type of device is capable of creating a routine
looking at the state.
For example, Smart Light Bulb or Switch.

I am attaching screenshots of the device and how it is not seen when trying
to create a routine on Alexa.

[image: Captura de Tela 2024-07-09 às 21.49.01.png]

[image: IMG_1613.PNG]


Em ter., 9 de jul. de 2024 às 21:21, Aruna Tennakoon <
***@***.***> escreveu:

**Comment by kakopappa** [comment]
Hi @marceloc312 

I'm sorry for not getting back to you sooner. 

Your attached screenshot is not visible. I think replying to an email with screenshots does not work in GitHub

I have created a switch device named: marceloc312 and I can see it in the Alexa routine. Check the image below.

![image](https://github.com/user-attachments/assets/a3247614-2991-4d4f-9dd8-8cf971e54d2e)
![image](https://github.com/user-attachments/assets/81cd8ed9-e770-4aeb-a027-2d37f7192b3f)

If you are not seeing the same, perhaps you could try the automation feature or scenes feature

**Comment by marceloc312** [comment]
Hi @kakopappa thanks for feedback. I don't know if I understood myself very well. But what I would like is to be able to use On/Off events as triggers for an action on Alexa. But I understand there may be limitations. If possible, I would like to see this feature in the future.
