### ISSUE TITLE
Requesting a template for a button press

### ISSUE THREAD

**Issue by Justnthenick** [sinricpro/feature-requests#68]
I need anything that will enable an output for 1 second then turn that output off. Literally a button press.

**Comment by sivar2311** [comment]
This is a question of implementation and is not dependent on SinricPro.

To point you in the right direction:

Inside the Callback 
- Set the desired output level
- Start a timer

Outside the callback
When the timer has expired flip the output level.

**Comment by kakopappa** [comment]
Hi @Justnthenick 

we have added a new device type called "Smart Button" for device templates which supports "button press" in the app v2.27.1.

better late than never
